% addpath('Distributions');
% myFiles = dir('Distributions/*.txt');
% numFiles = size(myFiles,1);
% KLMat = zeros(53,7);
% KLMatAlpha;
alphaVec = linspace(0.1,0.8,);
beta = 0.1;
gamma = 0.15;
N = 250;
% waittime = [0,8,16,24,32,40,48];
for i=1:length(alphaVec)
    alpha = alphaVec(i);
%     alpha = bI{i}{3}(1);
%     beta = bI{i}{3}(2);
%     gamma = bI{i}{3}(3);
%     numHouse
%     pause(waittime(i));
%     disp('Hello 1');
%     disp(i);
    myParams = [alpha; beta; gamma; N];
    command2 = 'g++ -O3 -static-libstdc++ -std=c++11 -fopenmp -o SIS2HouseMakeDist2 SIS2HouseMakeDist2.cpp';
    command3 = ['./SIS2HouseMakeDist2 ', num2str(alpha), ' ', num2str(beta), ' ', num2str(gamma), ' ', num2str(N)];
    status2 = system(command2); 
%     wait(5);
    status3 = system(command3);
    gillDist = findAvDist;
    command1='wolframscript -file test1.wls';
    csvwrite("myParams.csv",myParams);
    status1 = system(command1);
    mySS=csvread("mySS.csv");
    mySSSHH=csvread("mySSSHH.csv");
%     mySSMC=csvread("mySSMC.csv");
    FP = [mySS(1) mySS(2) 1-mySS(1)-mySS(2)];
    SHH = [1-mySSSHH(1)-mySSSHH(2) mySSSHH(1) mySSSHH(2)];
%     MC = [mySSMC(1) mySSMC(2) N-mySSMC(1)-mySSMC(2)]/N;
%     numState1 = bI{i}{3}(5);
%     numState2 = bI{i}{3}(6);
%     numState3 = bI{i}{3}(7);
%     sumState = numState1+numState2+numState3;
    G = gillDist;
%     KLMat(i,1) = alpha;
%     KLMat(i,2) = beta;
%     KLMat(i,3) = gamma;
%     KLMat(i,4) = numHouses;
    myDivFP = CalKLDiv(FP, G);
    myDivSHH = CalKLDiv(SHH, G);
%     myDivMC = CalKLDiv(MC,G);
    KLMatFP(i) = myDivFP;
    KLMatSHH(i) = myDivSHH;
%     KLMatMC(i) = myDivMC;
end

% a = KLMat(KLMat(:,2)==0.1 & KLMat(:,3)==0.15,:);
% plota = a(:,1);
% fpkldiva = a(:,5);
% shhkldiva = a(:,6);
% mckldiva = a(:,7);
figure;
hold on;
plot(alphaVec, KLMatFP,'r','LineWidth',2);
plot(alphaVec, KLMatSHH,'b','LineWidth',2);
plot(alphaVec, KLMatMC,'g','LineWidth',2);
legend('Fokker Planck','Single Household','Moment Closure');
% scatter(plota, fpkldiva,'rx');
% scatter(plota, shhkldiva,'bx');
xlabel('Alpha');
ylabel('KL-Divergence');
% 
% b = KLMat(KLMat(:,1)==0.1 & KLMat(:,3)==0.1,:);
% plotb = b(:,2);
% fpkldivb = b(:,5);
% shhkldivb = b(:,6);
% mckldivb = b(:,7);
% figure;
% hold on;
% plot(plotb, fpkldivb,'r','LineWidth',2);
% plot(plotb, shhkldivb,'b','LineWidth',2);
% plot(plotb, mckldivb,'g','LineWidth',2);
% legend('Fokker Planck','Single Household','Moment Closure');
% % scatter(plotb, fpkldivb,'rx');
% % scatter(plotb, shhkldivb,'bx');
% xlabel('Beta');
% ylabel('KL-Divergence');
% 
% g = KLMat(KLMat(:,1)==0.5 & KLMat(:,2)==0.5,:);
% plotg = g(:,3);
% fpkldivg = g(:,5);
% shhkldivg = g(:,6);
% mckldivg = g(:,7);
% figure;
% hold on;
% plot(plotg, fpkldivg,'r','LineWidth',2);
% plot(plotg, shhkldivg,'b','LineWidth',2);
% % plot(plotg, mckldivg,'g','LineWidth',2);
% legend('Fokker Planck','Single Household','Moment Closure');
% % scatter(plotg, fpkldivg,'rx');
% % scatter(plotg, shhkldivg,'bx');
% xlabel('Gamma');
% ylabel('KL-Divergence');